cc_binary(
    name = "regex_demo",
    srcs = ["regex_demo.cpp"],
)

cc_binary(
    name = "deduce_type_demo",
    srcs = ["deduce_type_demo.cpp"],
)

cc_binary(
   name = "lambda_demo",
   srcs = ["lambda_demo.cpp"],
)
